import {
  springb,
  python,
  java,
  javascript,
  reactjs,
  tailwind,
  nodejs,
  git,
  histoapp,
  ana,
  emotion,
  threejs,
  region,
  park,
  qr,
  pdfrag,
  roche,
  fhnw,
  ksa,
  kiosk,
  unibe,
  alpinelink,
  swissntech,
  docker,
  linux,
  Kotlin,
} from "../assets";

export const engagements = [
  {
    title: "sections.engagement.eng1.title",
    date: "sections.engagement.eng1.date",
    icon: "FaHandsHelping",
    description: [
      "sections.engagement.eng1.point1",
      "sections.engagement.eng1.point2",
      "sections.engagement.eng1.point3",
    ],
    download: "/UNESCO.pdf",
  },
  {
    title: "sections.engagement.eng2.title",
    date: "sections.engagement.eng2.date",
    icon: "FaRibbon",
    description: [
      "sections.engagement.eng2.point1",
      "sections.engagement.eng2.point2",
      "sections.engagement.eng2.point3",
    ],
    link: "https://www.20min.ch/story/schuelerin-20-schickt-krebskranke-auf-laufsteg-414065714213",
  },
  {
    title: "sections.engagement.eng3.title",
    date: "sections.engagement.eng3.date",
    icon: "FaUserGraduate",
    description: [
      "sections.engagement.eng3.point1",
      "sections.engagement.eng3.point3",
    ],
    link: "https://www.linkedin.com/posts/lifesciences_fhnw_antriebwirkung-deinantriebdeinewirkung-bachelorkampagne-activity-7338475308620120065-7BUt?utm_source=share&utm_medium=member_desktop&rcm=ACoAADqXAFkBt3n8bjfSjxTFeRNV4AziMieYPyI",
  },
];

export const navLinks = [
  {
    id: "about",
    title: "navbar.about",
  },
  {
    id: "tech",
    title: "navbar.tech",
  },
  {
    id: "work",
    title: "navbar.work",
  },
  {
    id: "projects",
    title: "navbar.projects",
  },
  {
    id: "engagement",
    title: "navbar.engagement",
  },
  {
    id: "contact",
    title: "navbar.contact",
  },
];

export const technologies = [
  { name: "Docker", icon: docker },
  { name: "Git", icon: git },
  { name: "Java", icon: java },
  { name: "JavaScript", icon: javascript },
  { name: "Kotlin", icon: Kotlin },
  { name: "Linux", icon: linux },
  { name: "Node.js", icon: nodejs },
  { name: "Python", icon: python },
  { name: "React", icon: reactjs },
  { name: "Spring Boot", icon: springb },
  { name: "Tailwind CSS", icon: tailwind },
  { name: "Three.js", icon: threejs },
];

export const experiences = [
  {
    title: "sections.experience.swissntech.title",
    company_name: "sections.experience.swissntech.company",
    icon: swissntech,
    iconBg: "#fafafa",
    date: "sections.experience.swissntech.date",
    current: true,
    points: [
      "sections.experience.swissntech.point1",
      "sections.experience.swissntech.point2",
      "sections.experience.swissntech.point3",
      "sections.experience.swissntech.point4",
    ],
  },
  {
    title: "sections.experience.eforms.title",
    company_name: "sections.experience.eforms.company",
    icon: unibe,
    iconBg: "#fafafa",
    date: "sections.experience.eforms.date",
    link: "https://www.unibe.ch",
    points: [
      "sections.experience.eforms.point1",
      "sections.experience.eforms.point2",
      "sections.experience.eforms.point3",
      "sections.experience.eforms.point4",
    ],
  },
  {
    title: "sections.experience.alpinelink.title",
    company_name: "sections.experience.alpinelink.company",
    icon: alpinelink,
    iconBg: "#fafafa",
    date: "sections.experience.alpinelink.date",
    link: "https://www.alpinelink.ch",
    current: true,
    points: [
      "sections.experience.alpinelink.point1",
      "sections.experience.alpinelink.point2",
      "sections.experience.alpinelink.point3",
      "sections.experience.alpinelink.point4",
    ],
  },
  {
    title: "sections.experience.roche.title",
    company_name: "sections.experience.roche.company",
    icon: roche,
    iconBg: "#fafafa",
    date: "sections.experience.roche.date",
    link: "https://www.roche.com",
    points: [
      "sections.experience.roche.point1",
      "sections.experience.roche.point2",
      "sections.experience.roche.point3",
      "sections.experience.roche.point4",
    ],
  },
  {
    title: "sections.experience.fhnw.title",
    company_name: "sections.experience.fhnw.company",
    icon: fhnw,
    iconBg: "#fafafa",
    date: "sections.experience.fhnw.date",
    link: "https://www.fhnw.ch/de",
    points: [
      "sections.experience.fhnw.point1",
      "sections.experience.fhnw.point2",
      "sections.experience.fhnw.point3",
      "sections.experience.fhnw.point4",
    ],
  },
  {
    title: "sections.experience.ksa.title",
    company_name: "sections.experience.ksa.company",
    icon: ksa,
    iconBg: "#fafafa",
    date: "sections.experience.ksa.date",
    link: "https://www.ksa.ch/de/kantonsspital-aarau/aufenthalt-und-besuch",
    points: [
      "sections.experience.ksa.point1",
      "sections.experience.ksa.point2",
      "sections.experience.ksa.point3",
      "sections.experience.ksa.point4",
    ],
  },
  {
    title: "sections.experience.bistro.title",
    company_name: "sections.experience.bistro.company",
    icon: kiosk,
    iconBg: "#fafafa",
    date: "sections.experience.bistro.date",
    points: [
      "sections.experience.bistro.point1",
      "sections.experience.bistro.point2",
      "sections.experience.bistro.point3",
      "sections.experience.bistro.point4",
    ],
  },
];

export const projects = [
  {
    name: "projects.pdfrag.name",
    description: "projects.pdfrag.description",
    tags: [
      { name: "RAG / LLM" },
      { name: "FastAPI" },
      { name: "React" },
      { name: "TypeScript" },
      { name: "Google Gemini" },
      { name: "Docker" },
      { name: "Terraform" },
      { name: "GCP" },
    ],
    image: pdfrag,
    source_code_link: "https://github.com/Sivanajani/pdfrag",
    glowColor: "#e3b958",
  },
  {
    name: "projects.histoapp.name",
    description: "projects.histoapp.description",
    tags: [
      { name: "React" },
      { name: "Spring Boot" },
      { name: "Kotlin" },
      { name: "Docker" },
      { name: "PACS / DICOM" },
      { name: "PostgreSQL" },
      { name: "Keycloak" },
    ],
    image: histoapp,
    source_code_link: "https://github.com/Sivanajani/HistoApp",
    glowColor: "#915EFF",
  },
  {
    name: "projects.emotion.name",
    description: "projects.emotion.description",
    tags: [
      { name: "PyTorch" },
      { name: "Vision Transformer" },
      { name: "Deep Learning" },
      { name: "Computer Vision" },
    ],
    image: emotion,
    source_code_link:
      "https://github.com/Sivanajani/Emotion-Recognition-with-Vision-Transformer",
    glowColor: "#135495",
  },
  {
    name: "projects.anamnese.name",
    description: "projects.anamnese.description",
    tags: [
      { name: "Python" },
      { name: "OCR" },
      { name: "Computer Vision" },
    ],
    image: ana,
    source_code_link: "https://github.com/Sivanajani/Anamnese-Formular",
    glowColor: "#2496ED",
  },
  {
    name: "projects.parkinson.name",
    description: "projects.parkinson.description",
    tags: [
      { name: "Python" },
      { name: "Pandas" },
      { name: "Data Science" },
      { name: "Feature Engineering" },
    ],
    image: park,
    source_code_link: "https://github.com/Sivanajani/Parkinson-Datensatzanalyse",
    glowColor: "#00788E",
  },
  {
    name: "projects.region.name",
    description: "projects.region.description",
    tags: [
      { name: "Python" },
      { name: "NumPy" },
      { name: "Image Processing" },
      { name: "Region Growing" },
    ],
    image: region,
    source_code_link: "https://github.com/Sivanajani/RegionGrowingLabeln",
    glowColor: "#273916",
  },
  {
    name: "projects.qrapp.name",
    description: "projects.qrapp.description",
    tags: [
      { name: "Python" },
      { name: "Tkinter" },
      { name: "Desktop App" },
    ],
    image: qr,
    source_code_link: "https://github.com/Sivanajani/qr-desktop-app",
    glowColor: "#4B5A65",
  },
];
